### ISSUE TITLE
Trouble with importing shared library with pyinstaller

### ISSUE THREAD

**Issue by finsberg** [ComputationalPhysiology/ap_features#15]
Consider the following code
```python
import numpy

print("Sucessfully imported numpy")
print(numpy.__version__)
```
If we try to build an executable with [pyinstaller](https://www.pyinstaller.org) with the following command
```
pyinstaller --onefile demo.py
```
<details>
<summary>Output</summary>

```
77 WARNING: Assuming this isn't an Anaconda environment or an additional venv/pipenv/... environment manager is being used on top because the conda-meta folder /Users/henriknf/local/src/ap_features/issue/venv/conda-meta doesn't exist.
87 INFO: PyInstaller: 4.5.1
87 INFO: Python: 3.8.8 (conda)
97 INFO: Platform: macOS-10.16-x86_64-i386-64bit
98 INFO: wrote /Users/henriknf/local/src/ap_features/issue/demo.spec
103 INFO: UPX is not available.
104 INFO: Extending PYTHONPATH with paths
['/Users/henriknf/local/src/ap_features/issue',
 '/Users/henriknf/local/src/ap_features/issue']
234 INFO: checking Analysis
245 INFO: Building because /Users/henriknf/local/src/ap_features/issue/demo.py changed
245 INFO: Initializing module dependency graph...
247 INFO: Caching module graph hooks...
254 INFO: Analyzing base_library.zip ...
2024 INFO: Processing pre-find module path hook distutils from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
2025 INFO: distutils: retargeting to non-venv dir '/Users/henriknf/miniconda3/lib/python3.8'
3793 INFO: Caching module dependency graph...
3900 INFO: running Analysis Analysis-00.toc
<CDLL 'libSystem.dylib', handle 119764710 at 0x7f8e40c3dcd0>
3906 INFO: Analyzing /Users/henriknf/local/src/ap_features/issue/demo.py
4497 INFO: Processing pre-find module path hook site from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks/pre_find_module_path/hook-site.py'.
4497 INFO: site: retargeting to fake-dir '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/fake-modules'
5815 INFO: Processing module hooks...
5816 INFO: Loading module hook 'hook-pkg_resources.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
5959 INFO: Processing pre-safe import module hook win32com from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/pre_safe_import_module/hook-win32com.py'.
6106 WARNING: Hidden import "pkg_resources.py2_warn" not found!
6106 WARNING: Hidden import "pkg_resources.markers" not found!
6108 INFO: Loading module hook 'hook-scipy.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
6109 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
6110 INFO: Loading module hook 'hook-lib2to3.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
6143 INFO: Loading module hook 'hook-_tkinter.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
6241 INFO: checking Tree
6248 INFO: checking Tree
6326 INFO: checking Tree
6327 INFO: Loading module hook 'hook-encodings.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
6377 INFO: Loading module hook 'hook-distutils.util.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
6380 INFO: Loading module hook 'hook-setuptools.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
6795 INFO: Loading module hook 'hook-pickle.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
6798 INFO: Loading module hook 'hook-heapq.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
6800 INFO: Loading module hook 'hook-difflib.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
6802 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
6803 INFO: Loading module hook 'hook-sysconfig.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
6809 INFO: Loading module hook 'hook-xml.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
6847 INFO: Loading module hook 'hook-numpy.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
6871 WARNING: Hidden import "six" not found!
6887 INFO: Import to be excluded not found: 'f2py'
6894 INFO: Loading module hook 'hook-distutils.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
6894 INFO: Loading module hook 'hook-numpy._pytesttester.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
6897 INFO: Loading module hook 'hook-setuptools.msvc.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
6909 INFO: Looking for ctypes DLLs
6942 INFO: Analyzing run-time hooks ...
6944 INFO: Including run-time hook '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py'
6946 INFO: Including run-time hook '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py'
6948 INFO: Including run-time hook '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_inspect.py'
6953 INFO: Looking for dynamic libraries
7084 INFO: Looking for eggs
7084 INFO: Python library not in binary dependencies. Doing additional searching...
7088 INFO: Using Python library /Users/henriknf/miniconda3/lib/libpython3.8.dylib
7094 INFO: Warnings written to /Users/henriknf/local/src/ap_features/issue/build/demo/warn-demo.txt
7126 INFO: Graph cross-reference written to /Users/henriknf/local/src/ap_features/issue/build/demo/xref-demo.html
7136 INFO: checking PYZ
7143 INFO: Building because toc changed
7143 INFO: Building PYZ (ZlibArchive) /Users/henriknf/local/src/ap_features/issue/build/demo/PYZ-00.pyz
7523 INFO: Building PYZ (ZlibArchive) /Users/henriknf/local/src/ap_features/issue/build/demo/PYZ-00.pyz completed successfully.
7527 INFO: EXE target arch: x86_64
7527 INFO: Code signing identity: None
7527 INFO: checking PKG
7529 INFO: Building because toc changed
7529 INFO: Building PKG (CArchive) PKG-00.pkg
14056 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
14059 INFO: Bootloader /Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/bootloader/Darwin-64bit/run
14059 INFO: checking EXE
14061 INFO: Building because toc changed
14061 INFO: Building EXE from EXE-00.toc
14064 INFO: Copying bootloader exe to /Users/henriknf/local/src/ap_features/issue/dist/demo
14065 INFO: Converting EXE to target arch (x86_64)
14082 INFO: Removing signature(s) from EXE
14138 INFO: Rewriting executable's macOS SDK version (11.1.0) to match the SDK version of the Python library (0.0.0) in order to avoid inconsistent behavior and potential UI issues in the frozen application.
14139 INFO: Fixing EXE for code signing /Users/henriknf/local/src/ap_features/issue/dist/demo
14141 INFO: Re-signing the EXE
14279 INFO: Building EXE from EXE-00.toc completed successfully.
```
</details>

we get an executable called `demo` in a folder called `dist`. Executing this yields

```
$ ./demo
Sucessfully imported numpy
1.20.3
````
Now if we do the same with `ap_feautures`, i.e

```python
import ap_features

print("Sucessfully imported ap_features")
print(ap_features.__version__)
```

```
pyinstaller --onefile demo.py
```

<details>
<summary>Output</summary>

```
43 WARNING: Assuming this isn't an Anaconda environment or an additional venv/pipenv/... environment manager is being used on top because the conda-meta folder /Users/henriknf/local/src/ap_features/issue/venv/conda-meta doesn't exist.
47 INFO: PyInstaller: 4.5.1
47 INFO: Python: 3.8.8 (conda)
54 INFO: Platform: macOS-10.16-x86_64-i386-64bit
55 INFO: wrote /Users/henriknf/local/src/ap_features/issue/demo.spec
59 INFO: UPX is not available.
59 INFO: Extending PYTHONPATH with paths
['/Users/henriknf/local/src/ap_features/issue',
 '/Users/henriknf/local/src/ap_features/issue']
183 INFO: checking Analysis
186 INFO: Building because /Users/henriknf/local/src/ap_features/issue/demo.py changed
186 INFO: Initializing module dependency graph...
187 INFO: Caching module graph hooks...
192 INFO: Analyzing base_library.zip ...
1896 INFO: Processing pre-find module path hook distutils from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
1897 INFO: distutils: retargeting to non-venv dir '/Users/henriknf/miniconda3/lib/python3.8'
3440 INFO: Caching module dependency graph...
3548 INFO: running Analysis Analysis-00.toc
<CDLL 'libSystem.dylib', handle 117379710 at 0x7fd7d8eaf820>
3553 INFO: Analyzing /Users/henriknf/local/src/ap_features/issue/demo.py
4148 INFO: Processing pre-find module path hook site from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks/pre_find_module_path/hook-site.py'.
4148 INFO: site: retargeting to fake-dir '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/fake-modules'
10936 INFO: Processing pre-safe import module hook win32com from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/pre_safe_import_module/hook-win32com.py'.
11853 INFO: Processing module hooks...
11853 INFO: Loading module hook 'hook-llvmlite.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
11857 INFO: Loading module hook 'hook-numba.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
11872 INFO: Loading module hook 'hook-scipy.linalg.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
11873 INFO: Loading module hook 'hook-pkg_resources.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
12195 WARNING: Hidden import "pkg_resources.py2_warn" not found!
12195 WARNING: Hidden import "pkg_resources.markers" not found!
12198 INFO: Loading module hook 'hook-scipy.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
12199 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
12199 INFO: Loading module hook 'hook-scipy.special._ufuncs.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
12200 INFO: Loading module hook 'hook-lib2to3.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
12234 INFO: Loading module hook 'hook-_tkinter.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
12338 INFO: checking Tree
12345 INFO: checking Tree
12407 INFO: checking Tree
12410 INFO: Loading module hook 'hook-scipy.spatial.transform.rotation.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
12436 INFO: Loading module hook 'hook-encodings.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
12489 INFO: Loading module hook 'hook-distutils.util.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
12495 INFO: Loading module hook 'hook-scipy.sparse.csgraph.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
12498 INFO: Loading module hook 'hook-setuptools.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
12963 INFO: Loading module hook 'hook-scipy.special._ellip_harm_2.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
12964 INFO: Loading module hook 'hook-pickle.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
12967 INFO: Loading module hook 'hook-heapq.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
12969 INFO: Loading module hook 'hook-scipy.stats._stats.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
12970 INFO: Loading module hook 'hook-difflib.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
12972 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
12974 INFO: Loading module hook 'hook-sysconfig.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
12980 INFO: Loading module hook 'hook-xml.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
13015 INFO: Loading module hook 'hook-numpy.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
13039 WARNING: Hidden import "six" not found!
13061 INFO: Import to be excluded not found: 'f2py'
13070 INFO: Loading module hook 'hook-distutils.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
13070 INFO: Loading module hook 'hook-numpy._pytesttester.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
13073 INFO: Loading module hook 'hook-setuptools.msvc.py' from '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks'...
13110 INFO: Looking for ctypes DLLs
13243 INFO: Analyzing run-time hooks ...
13251 INFO: Including run-time hook '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py'
13253 INFO: Including run-time hook '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py'
13255 INFO: Including run-time hook '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_inspect.py'
13256 INFO: Including run-time hook '/Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgres.py'
13276 INFO: Looking for dynamic libraries
13611 INFO: Looking for eggs
13611 INFO: Python library not in binary dependencies. Doing additional searching...
13613 INFO: Using Python library /Users/henriknf/miniconda3/lib/libpython3.8.dylib
13623 INFO: Warnings written to /Users/henriknf/local/src/ap_features/issue/build/demo/warn-demo.txt
13703 INFO: Graph cross-reference written to /Users/henriknf/local/src/ap_features/issue/build/demo/xref-demo.html
13729 INFO: checking PYZ
13732 INFO: Building because toc changed
13732 INFO: Building PYZ (ZlibArchive) /Users/henriknf/local/src/ap_features/issue/build/demo/PYZ-00.pyz
14814 INFO: Building PYZ (ZlibArchive) /Users/henriknf/local/src/ap_features/issue/build/demo/PYZ-00.pyz completed successfully.
14834 INFO: EXE target arch: x86_64
14834 INFO: Code signing identity: None
14835 INFO: checking PKG
14835 INFO: Building because toc changed
14835 INFO: Building PKG (CArchive) PKG-00.pkg
31841 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
31848 INFO: Bootloader /Users/henriknf/local/src/ap_features/issue/venv/lib/python3.8/site-packages/PyInstaller/bootloader/Darwin-64bit/run
31848 INFO: checking EXE
31849 INFO: Building because toc changed
31849 INFO: Building EXE from EXE-00.toc
31850 INFO: Copying bootloader exe to /Users/henriknf/local/src/ap_features/issue/dist/demo
31851 INFO: Converting EXE to target arch (x86_64)
31872 INFO: Removing signature(s) from EXE
31960 INFO: Rewriting executable's macOS SDK version (11.1.0) to match the SDK version of the Python library (0.0.0) in order to avoid inconsistent behavior and potential UI issues in the frozen application.
31961 INFO: Fixing EXE for code signing /Users/henriknf/local/src/ap_features/issue/dist/demo
31963 INFO: Re-signing the EXE
32287 INFO: Building EXE from EXE-00.toc completed successfully.
```

</details>

But when executing the executable

```
$ ./demo
Traceback (most recent call last):
  File "demo.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "ap_features/__init__.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "ap_features/features.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "ap_features/_c.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "ap_features/lib.py", line 56, in <module>
  File "ap_features/lib.py", line 42, in load_library
  File "ap_features/lib.py", line 42, in <genexpr>
  File "pathlib.py", line 1121, in iterdir
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/47/_3mbvrgn5gx2sqyjvqyyfbm40000gn/T/_MEITFw0Zk/ap_features'
[53717] Failed to execute script 'demo' due to unhandled exception!
````

Here I am using python3.8 on Mac OSX, but I get similar error on Windows with python3.9 also.

**Comment by finsberg** [comment]
The solution is to create at directory called `pyinstaller_hooks` and a file called `hook-ap_features.py` inside that folder with the following content
```python
from PyInstaller.utils.hooks import collect_dynamic_libs

binaries = collect_dynamic_libs("ap_features")
```
Now, instead of doing 
```
pyinstaller --onefile demo.py
```
you do 
```
pyinstaller --onefile --additional-hooks-dir=pyinstaller_hooks demo.py
```
The binary can now be executed and yields the expected result
```
 $ ./demo
Sucessfully imported ap_features
2021.0.0
```

**Comment by finsberg** [comment]
Note that I had some issues with this solution for Windows, but managed to solve it by modifying the hook like this

```python
from PyInstaller.utils.hooks import collect_dynamic_libs

binaries = collect_dynamic_libs("ap_features")
if len(binaries) == 0:
    import ap_features
    binaries = [(ap_features.lib.lib._name, "ap_features")]
```
